### ISSUE TITLE
SOLID

### ISSUE THREAD

**Issue by igorlimon** [istvanszekely23/PentaStagiuVara2018Homework#1]
metoda data face 2 actiuni. Valideaza numele si afiseaza un mesaj utilizatorului. In cazul in care vreau sa folosesc acest cod pentru o aplicatie web atunci nu voi mai avea nevoie de Console.WriteLine. https://en.wikipedia.org/wiki/SOLID
https://github.com/istvanszekely23/PentaStagiuVara2018Homework/blob/26c55d35551f9ac099e7d51894ea30f4f6d7d842/Module02Week01/Files/Program.cs#L49

**Comment by istvanszekely23** [comment]
`        private static bool IsValidName(string name)
        {
            if (!Regex.IsMatch(name, @"^[\p{L}\p{M}]+$") || name.Trim().Equals(""))
            {
                return false;
            }
            return true;
}`

**Comment by istvanszekely23** [comment]
Metoda a fost modificata, s-a adaugat un else pentru la linia 34 pentru a afisa mesajul de eroare.
`                    } else
                    {
                        Console.WriteLine("Invalid name: {0}", line);
}`
