### ISSUE TITLE
using

### ISSUE THREAD

**Issue by igorlimon** [istvanszekely23/PentaStagiuVara2018Homework#2]
iti recomand sa foloseti aici **using** deoarece daca apare vreo eroare pana la linia  fileStream.Close(); atunci stream va ramane deschis. :)
https://github.com/istvanszekely23/PentaStagiuVara2018Homework/blob/26c55d35551f9ac099e7d51894ea30f4f6d7d842/Module02Week01/Files/Program.cs#L71

**Comment by istvanszekely23** [comment]
Codul a fost modificat.
        private static void WriteToFile(string fileName, FileMode fileMode, FileAccess fileAcces)
        {
            using (FileStream fileStream = new FileStream(fileName, fileMode, fileAcces))
            {

                foreach (string name in people)
                {
                    string newName = name + "\n";
                    byte[] array = Encoding.ASCII.GetBytes(newName);
                    foreach (byte toWrite in array)
                    {
                        fileStream.WriteByte(toWrite);
                    }
                }
                fileStream.Close();
            }
}
